### ISSUE TITLE
Mesher error

### ISSUE THREAD

**Issue by kwschultz** [geodynamics/vq#30]
I'm not quite sure why this is failing. I have run this command before to use the mesher to create a vq fault model from the UCERF3 model in EQsim format.

![eqsim_to_vq](https://cloud.githubusercontent.com/assets/5606202/5344770/2e77ebe2-7ec7-11e4-8146-9b2719ab3726.png)

$ bash eqsim_to_vq.sh 2000 > mesher_output_2km.txt
LINE 356: Vertex 238 depth (-12999.4) is outside section bounds.
LINE 357: Vertex 239 depth (-12999.4) is outside section bounds.
LINE 723: Vertex 526 depth (-15499.9) is outside section bounds.
LINE 724: Vertex 527 depth (-15499.9) is outside section bounds.
LINE 908: Vertex 673 depth (-0.0509599) is outside section bounds.
... (many omitted)
LINE 111380: Vertex 86973 depth (-0.263752) is outside section bounds.
LINE 111383: Vertex 86976 depth (-0.263752) is outside section bounds.
LINE 111401: Vertex 86994 depth (-11799.7) is outside section bounds.
LINE 111402: Vertex 86995 depth (-11799.7) is outside section bounds.
LINE 111519: Vertex 87093 depth (-0.364131) is outside section bounds.
LINE 111522: Vertex 87096 depth (-0.364131) is outside section bounds.
LINE 111722: Vertex 87258 depth (-11799.9) is outside section bounds.
LINE 111723: Vertex 87259 depth (-11799.9) is outside section bounds.
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: quakelib::Element::set_max_slip
eqsim_to_vq.sh: line 23: 59923 Abort trap: 6           ../../vq/build/src/mesher $EDITOR_ARGS --export_file=UCERF3_fault_${ELEM_SIZE}.txt --export_file_type=text --export_file=UCERF3_fault_${ELEM_SIZE}.kml --export_file_type=kml --export_eqsim_geometry=UCERF3_${ELEM_SIZE}_EQSIM_out.dat --merge_duplicate_verts

**Comment by eheien** [comment]
Should be fixed by 944961a35160bffdb0b92e493d498c5e3490009e
