### ISSUE TITLE
Not writing final stress values to final sweeps

### ISSUE THREAD

**Issue by kwschultz** [geodynamics/vq#67]
It looks like VQ is not writing the final stress values to the HDF5 for the last sweep of an event.

We are hoping this is a one-off indexing error.

![unwritten_stress](https://cloud.githubusercontent.com/assets/5606202/6695381/0ab98812-cc9e-11e4-8153-1f08cf30b457.png)

**Comment by markyoder** [comment]
this looks like a problem in RunEvent.cpp:RunEvent::processStaticFailure(), specifically (more or less) in 
RunEvent::processBlocksSecondaryFailures(). basically, processStaticFailure() executes a call to processBlocksOrigFail(), which sets up the "original" failures (blocks' first-time failures) -- including setting initial-stress values. it then executes processBlocksSecondaryFail(), which reevaluates blocks that failed in previous sweeps. at the end of the processStaticFailure() script, a loop runs over the array global_failed_elements[ ] to set final stresses. however, this array is re-initialized every sweep, so only the original-failure blocks are updated; all secondary failures are skipped.

it looks like, in the script processBlocksSecondaryFail(), setInitStresses() (looping over all secondary fail blocks of course) should run at the begining, and then setFinalStresses() should run at the end. instead, only setInitStresses() runs at the end of the script. ... or am i not following the logic completely? commentary invited...

**Comment by markyoder** [comment]
i'm starting to think, also, that all of these negative stress values are not correct. most pointedly, 1) in the catalog from the older MKS version, there are no stresses<0. also, there are no original-slip events with final_stress<0 (all of them are 10-12<s_f<10-9 or so for my sample model.

**Comment by markyoder** [comment]
this problem resolved as part of recent merge/pull request #73.
